//WEATHER
export const GET_WEATHER = "GET_WEATHER";
export const REQUEST_WEATHER = "REQUEST_WEATHER";
export const DELETE_CARD_WEATHER = "DELETE_CARD_WEATHER";
export const UPDATE_CARD_WEATHER = "UPDATE_CARD_WEATHER";
